name: CI/CD Service

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      dry_run: # true = TEST, false = PROD
        required: true
        type: boolean

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Pour la Release
      packages: write   # Pour le Push GHCR
      id-token: write   # Pour l'authentification GHCR

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up QEMU (ARM support)
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64 # ðŸŽ¯ Ajout des plateformes cibles

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Calcul des Tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # ðŸš¨ Logique de Tag AdaptÃ©e au 'workflow_call' (seuls les inputs sont utilisables)
          tags: |
            # Tags DEV (Si Dry Run est vrai)
            type=raw,value=dev,enable=${{ inputs.dry_run }}
            type=raw,value=dev-${{ inputs.version }},enable=${{ inputs.dry_run }}
            
            # Tags PROD (Si Dry Run est faux)
            type=raw,value=latest,enable=${{ !inputs.dry_run }}
            type=raw,value=stable,enable=${{ !inputs.dry_run }}
            type=semver,pattern=v{{version}},value=${{ inputs.version }},enable=${{ !inputs.dry_run }}
            type=semver,pattern=v{{major}}.{{minor}},value=${{ inputs.version }},enable=${{ !inputs.dry_run }}
            type=semver,pattern=v{{major}},value=${{ inputs.version }},enable=${{ !inputs.dry_run }}


      - name: Build & Push (Multi-Arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: BW_VERSION=${{ inputs.version }}
          platforms: linux/amd64,linux/arm64 # ðŸ“¢ Push multi-arch (nÃ©cessite Buildx)

      - name: GitHub Release
        if: inputs.dry_run == false
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.version }}
          name: v${{ inputs.version }}
          generate_release_notes: true
          make_latest: true